### ISSUE TITLE
npm i -g craziness > Error: craziness@0.0.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by AxDSan** [karliky/CrazinessJS#1]
Saludos karliky, he tenido este problema en cuanto a la construcción del addon se refiere. ya que este me falla cuando voy a hacer el inicio de la instalación.

Aqui el LOG del error: https://paste.ee/r/EGEpJ/0

Pasos a reproducir:

1. Clonié el repositorio con `git clone --recurse-submodules git://github.com/karliky/CrazinessJS.git`
2. Descargue todo "build tools" y "tool-chains" necesarios para la instalación del addon.
3. Ejecuté el comando `npm install craziness`

Me salio el error que ves en el log.

Gracias de antemano por cualquier tipo de ayuda que me puedas brindar.
Saludos.

**Comment by karliky** [comment]
Me temo que esta librería esta deprecada y no mantenida. La alternativa que yo uso actualmente es Robot-js https://github.com/Robot/robot-js

Debería servirte para lo mismo y mucho más! Un saludo!

**Comment by AxDSan** [comment]
¡Muchas gracias!
